### ISSUE TITLE
media sync returning OK with some media unsynced

### ISSUE THREAD

**Issue by noffle** [digidem/mapeo-core#15]
Saw this on Travis (Node 8, macOS):

```
# sync: mobile <-> mobile photos
ok 96 undefined
ok 97 undefined
ok 98 null
ok 99 null
ok 100 api 1 has targets
ok 101 api 2 has targets
ok 102 replication complete
ok 103 null
ok 104 should be equivalent
ok 105 null
not ok 106 should be equivalent
  ---
    operator: deepEqual
    expected: |-
      [ 'original/goodbye_world.png', 'preview/foo-0.jpg', 'preview/foo-1.jpg', 'preview/foo-2.jpg', 'preview/foo-3.jpg', 'preview/foo-4.jpg', 'preview/goodbye_world.png', 'thumbnail/foo-0.jpg', 'thumbnail/foo-1.jpg', 'thumbnail/foo-2.jpg', 'thumbnail/foo-3.jpg', 'thumbnail/foo-4.jpg', 'thumbnail/goodbye_world.png' ]
    actual: |-
      [ 'original/goodbye_world.png', 'preview/foo-1.jpg', 'preview/foo-2.jpg', 'preview/foo-3.jpg', 'preview/foo-4.jpg', 'preview/goodbye_world.png', 'thumbnail/foo-1.jpg', 'thumbnail/foo-2.jpg', 'thumbnail/foo-3.jpg', 'thumbnail/foo-4.jpg', 'thumbnail/goodbye_world.png' ]
    at: <anonymous> (/Users/travis/build/digidem/mapeo-core/test/sync.js:365:13)
    stack: |-
      Error: should be equivalent
          at Test.assert [as _assert] (/Users/travis/build/digidem/mapeo-core/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/Users/travis/build/digidem/mapeo-core/node_modules/tape/lib/test.js:77:32)
          at Test.tapeDeepEqual (/Users/travis/build/digidem/mapeo-core/node_modules/tape/lib/test.js:423:10)
          at Test.bound [as deepEquals] (/Users/travis/build/digidem/mapeo-core/node_modules/tape/lib/test.js:77:32)
          at /Users/travis/build/digidem/mapeo-core/test/sync.js:365:13
          at /Users/travis/build/digidem/mapeo-core/node_modules/safe-fs-blob-store/index.js:87:10
          at /Users/travis/build/digidem/mapeo-core/node_modules/async/dist/async.js:969:16
          at next (/Users/travis/build/digidem/mapeo-core/node_modules/async/dist/async.js:5225:18)
          at /Users/travis/build/digidem/mapeo-core/node_modules/async/dist/async.js:473:16
          at next (/Users/travis/build/digidem/mapeo-core/node_modules/async/dist/async.js:5329:29)
```

https://travis-ci.org/digidem/mapeo-core/jobs/517564267

**Comment by karissa** [comment]
Could this be an off by one error?

**Comment by noffle** [comment]
What do you mean?

**Comment by karissa** [comment]
fixed!
