### ISSUE TITLE
Node 10 compatibility

### ISSUE THREAD

**Issue by noffle** [digidem/mapeo-core#16]
This seems to be very reproducible, and happens on all of {Windows,macOS,Linux}:

```
# sync: replication of a simple observation with media
ok 48 undefined
ok 49 null
ok 50 null
ok 51 obs1 created
ok 52 api 1 has targets
ok 53 api 2 has targets
not ok 54 Error: unexpected non-ready-signal byte received
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: unexpected non-ready-signal byte received]
    at: EventEmitter.<anonymous> (/home/travis/build/digidem/mapeo-core/test/sync.js:102:11)
    stack: |-
      Error: unexpected non-ready-signal byte received
          at Writable.HandshakeStream.w._write (/home/travis/build/digidem/mapeo-core/node_modules/handshake-stream/index.js:31:21)
          at doWrite (_stream_writable.js:410:12)
          at writeOrBuffer (_stream_writable.js:394:5)
          at Writable.write (_stream_writable.js:294:11)
          at Duplexify._write (/home/travis/build/digidem/mapeo-core/node_modules/duplexify/index.js:208:22)
          at doWrite (/home/travis/build/digidem/mapeo-core/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:428:64)
          at writeOrBuffer (/home/travis/build/digidem/mapeo-core/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:417:5)
          at Duplexify.Writable.write (/home/travis/build/digidem/mapeo-core/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:334:11)
          at DestroyableTransform.ondata (/home/travis/build/digidem/mapeo-core/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:662:20)
          at DestroyableTransform.emit (events.js:189:13)
```

https://travis-ci.org/digidem/mapeo-core/jobs/517564271

**Comment by karissa** [comment]
can we ignore node 10 for now? I still haven't been using it locally because level doesn't seem to like compiling with it

**Comment by noffle** [comment]
I'm not running it either. I think we can safely ignore for now.

**Comment by noffle** [comment]
Currently blocked by https://github.com/noffle/handshake-stream/issues/1

**Comment by noffle** [comment]
Fixed.
